import { pass, fail, ROOT } from '../helpers.mjs';
import { join } from 'path';
import { pathToFileURL } from 'url';
import { BROWSER_LIKE_USER_AGENT, MACOS_BROWSER_LIKE_USER_AGENT } from '../../providers/_http.mjs';

console.log('\nProvider — wanted');

const mod = await import(pathToFileURL(join(ROOT, 'providers/wanted.mjs')).href);
const wanted = mod.default;
const {
  normalizeWantedJob,
  buildWantedApiUrl,
  wantedRequestHeaders,
  isCloudFrontBody,
  CLOUDFRONT_MESSAGE,
} = mod;

if (wanted.id === 'wanted') pass('wanted.id is "wanted"');
else fail(`wanted.id is ${JSON.stringify(wanted.id)}`);

const url = buildWantedApiUrl('백엔드', 20, 0);
if (url.includes('keyword=') && url.startsWith('https://www.wanted.co.kr/api/v4/jobs')) {
  pass('buildWantedApiUrl builds expected API URL');
} else {
  fail(`buildWantedApiUrl = ${url}`);
}

const job = normalizeWantedJob(
  {
    id: 12345,
    position: '  백엔드 엔지니어  ',
    company: { name: '  테스트컴퍼니  ' },
    address: { location: '서울', district: '강남구' },
  },
  'Fallback',
);
if (
  job &&
  job.title === '백엔드 엔지니어' &&
  job.url === 'https://www.wanted.co.kr/wd/12345' &&
  job.company === '테스트컴퍼니' &&
  job.location === '서울 강남구'
) {
  pass('normalizeWantedJob maps fields correctly');
} else {
  fail(`normalizeWantedJob = ${JSON.stringify(job)}`);
}

if (normalizeWantedJob({ id: 1 }) === null) pass('normalizeWantedJob drops rows without title');
else fail('normalizeWantedJob should drop rows without title');

const hdr = wantedRequestHeaders();
if (
  hdr['User-Agent'] === BROWSER_LIKE_USER_AGENT &&
  /application\/json/.test(hdr.Accept) &&
  /ko-KR/.test(hdr['Accept-Language'])
) {
  pass('wantedRequestHeaders uses browser UA + JSON accept + ko-KR');
} else {
  fail(`wantedRequestHeaders = ${JSON.stringify(hdr)}`);
}

if (isCloudFrontBody('Error from CloudFront') && !isCloudFrontBody('{"data":[]}')) {
  pass('isCloudFrontBody detects CloudFront interstitial text');
} else {
  fail('isCloudFrontBody should match CloudFront body text only');
}

const okPayload = {
  data: [{ id: 99, position: 'NestJS 백엔드', company: { name: 'Acme' }, address: { location: '서울' } }],
  links: {},
};

{
  const rows = await wanted.fetch(
    { name: 'Wanted — 백엔드', searchKeywords: '백엔드', max_pages: 1 },
    { fetchJson: async () => okPayload, sleep: async () => {} },
  );
  if (rows.length === 1 && rows[0].url === 'https://www.wanted.co.kr/wd/99' && rows[0].title === 'NestJS 백엔드') {
    pass('wanted.fetch maps a public listing JSON page');
  } else {
    fail(`wanted.fetch happy path = ${JSON.stringify(rows)}`);
  }
}

{
  const uas = [];
  try {
    await wanted.fetch(
      { name: 'Wanted — 백엔드', searchKeywords: '백엔드', max_pages: 1 },
      {
        fetchJson: async (_url, opts) => {
          uas.push(opts?.headers?.['User-Agent']);
          const err = new Error('HTTP 403 Forbidden');
          err.status = 403;
          err.body = '<html>Generated by cloudfront</html>';
          throw err;
        },
        sleep: async () => {},
      },
    );
    fail('wanted.fetch should throw on persistent CloudFront 403');
  } catch (err) {
    if (
      err.message === CLOUDFRONT_MESSAGE &&
      err.status === 403 &&
      uas[0] === BROWSER_LIKE_USER_AGENT &&
      uas.includes(MACOS_BROWSER_LIKE_USER_AGENT)
    ) {
      pass('wanted.fetch wraps CloudFront 403 and tries the macOS UA once');
    } else {
      fail(`CloudFront 403 handling: message=${err.message} status=${err.status} uas=${JSON.stringify(uas)}`);
    }
  }
}

{
  let calls = 0;
  const rows = await wanted.fetch(
    { name: 'Wanted — 백엔드', searchKeywords: '백엔드', max_pages: 1 },
    {
      fetchJson: async (_url, opts) => {
        calls += 1;
        const ua = opts?.headers?.['User-Agent'];
        if (ua === BROWSER_LIKE_USER_AGENT) {
          const err = new Error('HTTP 403');
          err.status = 403;
          throw err;
        }
        return okPayload;
      },
      sleep: async () => {},
    },
  );
  if (calls >= 2 && rows.length === 1 && rows[0].company === 'Acme') {
    pass('wanted.fetch recovers from 403 by retrying with the fallback UA');
  } else {
    fail(`UA fallback recovery: calls=${calls} rows=${JSON.stringify(rows)}`);
  }
}
